name: Version Bump
description: Bump the version of a project
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  currentVersion:
    description: The current version of the project
    required: false
    default: "0.0.0"
  increment:
    description: The increment to apply to the version
    required: true
    default: "patch"
  prefix:
    description: The prefix to add to the version
    required: false
  suffix:
    description: The suffix to add to the version
    required: false
outputs:
  version:
    description: The new version
  
